-- USING THE DATABASE
USE GLIB;

-- DROPPING A TABLE, IF EXISTS
DROP TABLE IF EXISTS STUDENT;

-- CREATING A TABLE
CREATE TABLE STUDENT (
  StudentId int NOT NULL AUTO_INCREMENT,
  FullName varchar(100) NOT NULL, 
  Email varchar(100) NOT NULL,
  CONSTRAINT StudentId_PK PRIMARY KEY (StudentId)
);

-- UPDATING A TABLE
ALTER TABLE STUDENT ADD (FullAddress varchar(200) NULL, Phone varchar(12) NULL);
ALTER TABLE STUDENT ADD IsActive char(1) NOT NULL; -- Y: yes or N: no
