USE GLIB;

-- SELECTING / RETRIEVING DATA FROM A TABLE
SELECT count(*) FROM STUDENT;
-- SELECT FullName FROM STUDENT where fulladdress like '%center%';

-- INSERTING DATA IN A TABLE
/*

insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Winnah Hardbattle', 'whardbattle0@ustream.tv', '2 Sullivan Crossing', '714-909-3343', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Dacey Parnham', 'dparnham1@sourceforge.net', '90 Onsgard Trail', '756-982-8278', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Bibbye Mulles', 'bmulles2@digg.com', '88106 Norway Maple Plaza', '829-125-2831', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Portia Hopkins', 'phopkins3@sakura.ne.jp', '08 Arizona Center', '556-398-7102', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Drusilla Macieja', 'dmacieja4@shinystat.com', '26459 Northland Terrace', '773-998-3877', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Nowell Eva', 'neva5@simplemachines.org', '360 Badeau Circle', '435-542-7229', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Cleon Form', 'cform6@1und1.de', '45397 Helena Pass', '886-249-1867', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Dulcine Foxhall', 'dfoxhall7@lulu.com', '2 Vahlen Parkway', '670-673-9501', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Moore Adderley', 'madderley8@ebay.co.uk', '4786 Talmadge Center', '602-863-4746', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Melody Forsaith', 'mforsaith9@skype.com', '0 Valley Edge Plaza', '180-948-5379', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Vasili Rosle', 'vroslea@nytimes.com', '658 Onsgard Court', '448-735-9837', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Benedetto Liverock', 'bliverockb@washingtonpost.com', '494 Duke Road', '279-614-7390', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Sephira Pinel', 'spinelc@amazon.de', '9675 Green Way', '285-227-7395', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Diego Jacobowits', 'djacobowitsd@tumblr.com', '336 Northland Court', '800-789-0359', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Mic Prester', 'mprestere@amazon.co.jp', '1 Raven Drive', '440-722-9724', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Dulciana Semkins', 'dsemkinsf@cbsnews.com', '0 High Crossing Avenue', '251-453-3198', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Alicea Mowsdill', 'amowsdillg@studiopress.com', '36 Mockingbird Alley', '418-831-9257', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Arlin Gilyott', 'agilyotth@deliciousdays.com', '7 Holmberg Junction', '143-183-1347', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Davida Danson', 'ddansoni@sciencedaily.com', '62 Meadow Valley Street', '953-252-9247', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Denna Welland', 'dwellandj@theatlantic.com', '7876 Starling Junction', '399-623-9947', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Lily Roycroft', 'lroycroftk@flickr.com', '090 Banding Trail', '170-942-7577', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Addy Peto', 'apetol@amazon.de', '475 Springview Drive', '727-176-8616', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Hyacintha Nucci', 'hnuccim@statcounter.com', '69 Saint Paul Alley', '199-724-2438', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Chane De Anesy', 'cden@google.co.uk', '62241 Manufacturers Point', '661-236-6252', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Cicely Slayford', 'cslayfordo@1688.com', '149 Kingsford Circle', '751-101-6971', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Bobby Karpeev', 'bkarpeevp@yolasite.com', '56029 Bartelt Trail', '390-569-3415', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Sargent Malt', 'smaltq@nasa.gov', '552 Becker Junction', '253-622-0853', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Lou Robilart', 'lrobilartr@tamu.edu', '664 Dryden Lane', '278-294-8641', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Annabela Charlson', 'acharlsons@creativecommons.org', '7737 Golf Crossing', '693-461-1473', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Elsinore Lumsdall', 'elumsdallt@mysql.com', '80 Cherokee Junction', '324-343-0663', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Toma Midford', 'tmidfordu@twitpic.com', '35486 Scofield Circle', '649-403-8744', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Laurena Claworth', 'lclaworthv@abc.net.au', '777 Westend Place', '202-463-2111', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Donavon Luquet', 'dluquetw@wordpress.com', '2 Bunting Park', '285-585-1113', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Diena Berkowitz', 'dberkowitzx@google.co.jp', '1 Anniversary Junction', '208-773-3381', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Winny Longrigg', 'wlongriggy@yellowpages.com', '7742 South Place', '444-251-7674', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Becka Lampaert', 'blampaertz@nih.gov', '5955 Dakota Way', '444-939-2100', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Gregoire MacGahey', 'gmacgahey10@nps.gov', '588 Jenifer Pass', '912-404-6805', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Joaquin Greenan', 'jgreenan11@loc.gov', '6 Rusk Drive', '925-958-7951', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Lesley Grundy', 'lgrundy12@ftc.gov', '0 Dayton Trail', '500-136-7421', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Frederica Douglass', 'fdouglass13@bandcamp.com', '95111 Ronald Regan Plaza', '506-142-9638', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Alphonso Leese', 'aleese14@chicagotribune.com', '971 Delaware Hill', '628-926-0715', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Caron La Vigne', 'cla15@sogou.com', '03 Almo Trail', '125-847-8445', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Penelopa Storey', 'pstorey16@vimeo.com', '5 Manitowish Circle', '116-874-5553', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Caddric Tavernor', 'ctavernor17@senate.gov', '0 Victoria Terrace', '970-255-4472', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Franny Dingate', 'fdingate18@adobe.com', '1825 Fairfield Hill', '867-593-4838', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Wynn Fawks', 'wfawks19@dell.com', '110 Sachtjen Plaza', '566-694-8868', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Cybill Sheriff', 'csheriff1a@earthlink.net', '7749 Dunning Point', '384-245-4998', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Ashley Shee', 'ashee1b@elegantthemes.com', '1797 Golden Leaf Street', '900-849-4444', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Tonya Ferencz', 'tferencz1c@nationalgeographic.com', '7549 Merchant Crossing', '944-283-4200', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Alexio Ivakin', 'aivakin1d@hhs.gov', '82 Quincy Center', '651-649-6459', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Gustie Howieson', 'ghowieson1e@comsenz.com', '755 Arapahoe Park', '859-650-3195', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Garvey Mangeney', 'gmangeney1f@mozilla.com', '74944 Green Ridge Way', '109-630-1482', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Alphonso Kelinge', 'akelinge1g@barnesandnoble.com', '658 Armistice Place', '958-902-1603', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Noemi Gogarty', 'ngogarty1h@dagondesign.com', '58 Spenser Parkway', '208-390-3272', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Tildy Bernardino', 'tbernardino1i@youtube.com', '1496 Manitowish Avenue', '730-704-6530', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Arie Maplethorp', 'amaplethorp1j@lulu.com', '0663 Everett Pass', '474-292-2037', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Abbi Cutchey', 'acutchey1k@vimeo.com', '38 Holy Cross Parkway', '445-712-4597', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Ingrim Scimonelli', 'iscimonelli1l@disqus.com', '276 Mallard Center', '646-913-9385', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Mufi Harber', 'mharber1m@hibu.com', '6960 Barnett Hill', '606-758-8478', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Christa Handford', 'chandford1n@accuweather.com', '01 Memorial Terrace', '278-935-0068', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Andrey Eymer', 'aeymer1o@bravesites.com', '0380 Riverside Center', '798-309-2891', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Lucinda McGinny', 'lmcginny1p@tinyurl.com', '8782 Harper Court', '661-515-2115', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Coralyn Woolfitt', 'cwoolfitt1q@nydailynews.com', '7 Sycamore Parkway', '584-668-9948', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Odo Loughman', 'oloughman1r@php.net', '4 Gina Pass', '224-874-8997', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Thomasa Merrifield', 'tmerrifield1s@ycombinator.com', '311 Norway Maple Center', '516-776-9525', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Nichol Nussey', 'nnussey1t@disqus.com', '68297 Melrose Place', '770-512-0023', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Ivor Pallent', 'ipallent1u@theglobeandmail.com', '0 Northport Terrace', '428-727-5938', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Alta Choak', 'achoak1v@cbsnews.com', '7 Morning Circle', '375-981-1479', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Sella Bartol', 'sbartol1w@bbb.org', '537 Meadow Ridge Street', '910-375-9796', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Felicle Warlock', 'fwarlock1x@stumbleupon.com', '4862 Kinsman Circle', '429-950-0719', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Caron Iglesiaz', 'ciglesiaz1y@pinterest.com', '6882 Buell Court', '876-848-8954', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Ezequiel Lilian', 'elilian1z@creativecommons.org', '171 Carpenter Circle', '211-152-1475', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Stanwood Tregiddo', 'stregiddo20@sitemeter.com', '8 Roxbury Trail', '767-393-2817', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Thorndike Myles', 'tmyles21@exblog.jp', '1900 Dovetail Park', '258-306-0709', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Hillary Stollenbecker', 'hstollenbecker22@cbsnews.com', '38 Michigan Junction', '269-112-5855', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Nanette Walbrook', 'nwalbrook23@xrea.com', '275 Amoth Crossing', '910-457-8587', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Anabella Gwyneth', 'agwyneth24@tumblr.com', '28 Buell Plaza', '976-222-0469', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Anabelle Atty', 'aatty25@taobao.com', '69 Melby Drive', '919-392-0340', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Godfry Devenport', 'gdevenport26@china.com.cn', '20 Petterle Alley', '896-869-5345', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Mirabelle Gally', 'mgally27@ustream.tv', '6879 Corscot Pass', '841-107-8910', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Reagen Tidgewell', 'rtidgewell28@barnesandnoble.com', '9 Riverside Circle', '512-756-9080', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Ginger Gurling', 'ggurling29@utexas.edu', '1666 Caliangt Drive', '348-716-8714', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Willie Over', 'wover2a@telegraph.co.uk', '20811 Golf Trail', '863-166-6614', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Tammie Woltering', 'twoltering2b@pbs.org', '991 Dakota Way', '543-828-8897', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Beverie Fautly', 'bfautly2c@nymag.com', '66 Kipling Street', '668-163-9580', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Lucille Swale', 'lswale2d@answers.com', '3470 Moose Crossing', '437-816-7543', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Aurie Snarr', 'asnarr2e@mayoclinic.com', '4666 Schurz Trail', '965-506-9268', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Dallis Scorey', 'dscorey2f@123-reg.co.uk', '804 Maywood Point', '197-253-2605', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Donni Spearing', 'dspearing2g@tripadvisor.com', '929 Columbus Center', '573-446-9450', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Warner Heater', 'wheater2h@angelfire.com', '90937 Northview Trail', '189-304-3960', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Otes Wickwar', 'owickwar2i@redcross.org', '0101 Ohio Park', '270-153-4574', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Jeanne McLise', 'jmclise2j@china.com.cn', '57 Pierstorff Avenue', '877-875-7049', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Mercy Etherson', 'metherson2k@netvibes.com', '4152 Caliangt Point', '704-427-9003', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Foster Reavell', 'freavell2l@eepurl.com', '5276 Debs Lane', '720-710-4109', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Saw Woodall', 'swoodall2m@google.com.hk', '22 Holmberg Way', '843-436-4429', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Myrvyn Thurlbourne', 'mthurlbourne2n@360.cn', '7838 Blackbird Street', '988-797-3306', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Sena Cattonnet', 'scattonnet2o@shutterfly.com', '752 Eggendart Crossing', '246-416-7607', 'N');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Roscoe Serjent', 'rserjent2p@moonfruit.com', '8 Garrison Circle', '558-568-8125', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Eliot Riggs', 'eriggs2q@noaa.gov', '9 Veith Point', '944-886-9713', 'Y');
insert into Student (FullName, Email, FullAddress, Phone, IsActive) values ('Adora Chrichton', 'achrichton2r@cocolog-nifty.com', '013 Straubel Trail', '704-747-7459', 'Y');

-- */